/// <reference lib="deno.ns" />

import { serveDir } from "@std/http/file-server";
import treasury from "./api/treasury.ts";
import health from "./api/health.ts";
import share from "./api/share.ts";

// =============================================================================
// API Router
// =============================================================================

type RouteHandler = (req: Request) => Promise<Response> | Response;

// Minimal routing table for API endpoints
const routes: Record<string, RouteHandler> = {
  "GET /api/treasury": treasury,
  "GET /api/health": health,
};

function routeKey(req: Request): string {
  const { pathname } = new URL(req.url);
  return `${req.method.toUpperCase()} ${pathname}`;
}

// =============================================================================
// Main Server
// =============================================================================

Deno.serve(async (req) => {
  const url = new URL(req.url);

  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type",
      },
    });
  }

  // 1) Share pages: /s/<project> landing + /s/<project>.png card image
  if (req.method === "GET" && url.pathname.startsWith("/s/")) {
    return share(req);
  }

  // 2) API routes
  if (url.pathname.startsWith("/api/")) {
    const handler = routes[routeKey(req)];
    if (!handler) {
      return new Response(JSON.stringify({ error: "Not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }
    return handler(req);
  }

  // 3) Static files from React Router build output
  const res = await serveDir(req, {
    fsRoot: "build/client",
    quiet: true,
  });

  // 4) SPA fallback for client-side routing
  if (res.status === 404) {
    // Try SPA fallback first (generated by React Router prerender)
    try {
      const fallbackReq = new Request(new URL("/__spa-fallback.html", req.url), req);
      const fallbackRes = await serveDir(fallbackReq, {
        fsRoot: "build/client",
        quiet: true,
      });
      if (fallbackRes.status === 200) {
        return fallbackRes;
      }
    } catch {
      // Fallback to index.html
    }

    // Try index.html as final fallback
    try {
      const indexReq = new Request(new URL("/index.html", req.url), req);
      const indexRes = await serveDir(indexReq, {
        fsRoot: "build/client",
        quiet: true,
      });
      if (indexRes.status === 200) {
        return indexRes;
      }
    } catch {
      // Return original 404
    }
  }

  return res;
});

console.log("🚀 Server running - serving static files + API");

